project:
  type: website
  output-dir: docs

website:
  title: "Kudurupaka Vamshi Krishna"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Talks"
        href: talks/index.qmd
      - text: "Teaching & Outreach"
        href: teaching_outreach/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Contact"
        href: contact/index.qmd

format:
  html:
    theme: cosmo
    css: styles/styles.css
    toc: true
